pipeline {
	agent any
	stages {

		stage('Lint HTML') {
			steps {
				sh 'cd Deploy/ && tidy index.html'
			}
		}

		
		stage('Building Docker Image') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
					sh '''
						cd Deploy/ && docker build -t db7gs/webserver-image:v2 .
					'''
				}
			}
		}

		stage('Pushing Image To Dockerhub') {
			steps {
				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD']]){
					sh '''
						docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD docker.io
						docker push db7gs/webserver-image:v2
					'''
				}
			}
		}

		stage('Set current kubectl context') {
			steps {
				withAWS(region:'us-west-2', credentials:'udacity1') {
					sh '''
						kubectl config use-context arn:aws:eks:us-west-2:135063476550:cluster/capstoneudacityclusterproject
					'''
				}
			}
		}

		stage('Deploy blue container') {
			steps {
				withAWS(region:'us-west-2', credentials:'udacity1') {
					sh '''
						cd Deploy/ && kubectl apply -f ./blue-controller.json
					'''
				}
			}
		}

		stage('Deploy green container') {
			steps {
				withAWS(region:'us-west-1', credentials:'udacity1') {
					sh '''
						cd Deploy/ && kubectl apply -f ./green-controller.json
					'''
				}
			}
		}

		stage('Create the service in the cluster, redirect to blue') {
			steps {
				withAWS(region:'us-west-1', credentials:'udacity1') {
					sh '''
						cd Deploy/ && kubectl apply -f ./blue-service.json
					'''
				}
			}
		}

		stage('Wait user approve') {
            steps {
                input "Ready to redirect traffic to green?"
            }
        }

		stage('Create the service in the cluster, redirect to green') {
			steps {
				withAWS(region:'us-west-2', credentials:'udacity1') {
					sh '''
						cd Deploy/ && kubectl apply -f ./green-service.json
					'''
				}
			}
		}

	}
}